#!/bin/bash
set -ex
# should be run from the e.g. dev/main
current_dir=${PWD##*/}
git clone git@github.com:zou3519/vllm.git vllm-$current_dir
cd vllm-$current_dir
git remote add upstream git@github.com:vllm-project/vllm.git
git pull --rebase upstream main
uv pip install -r requirements/build.txt
pre-commit install --hook-type pre-commit --hook-type commit-msg
