#!/bin/bash
set -ex
if [ -z "$PT_ROOT" ]; then
    echo "Need to set PT_ROOT"
    exit 1
fi
pushd $PT_ROOT/master
git worktree add ../$1
pushd ../$1
# $2 is python version. One can do 'feature my-feature 2.7'
mkenv $2
git subup
ctags -R --exclude=third_party --exclude=torch/lib --exclude=build --exclude=caffe2
popd
popd
cd $PT_ROOT/$1
