#!/bin/bash
PYTHON_VERSION=${1:-3}
conda create -y -p $PWD-env python=$PYTHON_VERSION numpy pyyaml mkl mkl-include setuptools cmake cffi pytest ipython
conda activate $PWD-env
pip install ninja
pip install ghstack
